# Generated by Django 3.2.3 on 2021-07-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='工号')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('sex', models.CharField(max_length=4, verbose_name='性别')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('keshi', models.CharField(max_length=50, verbose_name='科室')),
                ('duty', models.CharField(max_length=20, verbose_name='职务')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'db_table': 'userinfo',
            },
        ),
        migrations.CreateModel(
            name='Userworklog',
            fields=[
                ('id', models.CharField(max_length=6, verbose_name='工号')),
                ('index', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='索引')),
                ('date', models.DateField(verbose_name='日期')),
                ('needs', models.CharField(max_length=4, verbose_name='系统需求')),
                ('place', models.CharField(max_length=30, verbose_name='科室')),
                ('qsort', models.CharField(max_length=16, verbose_name='问题类型')),
                ('qdescribe', models.CharField(max_length=30, verbose_name='问题描述')),
                ('fisstatu', models.CharField(max_length=10, verbose_name='完成情况')),
                ('note', models.CharField(max_length=60, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '工作日志',
                'db_table': 'Userworklog',
            },
        ),
    ]
