# Generated by Django 3.2.3 on 2021-06-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='工号')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('sex', models.IntegerField(verbose_name='性别')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('keshi', models.CharField(max_length=50, verbose_name='科室')),
                ('duty', models.CharField(max_length=20, verbose_name='职务')),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
