# Generated by Django 3.2.3 on 2021-06-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='工号'),
        ),
    ]
