# Generated by Django 3.2.3 on 2021-06-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog_web', '0002_alter_userinfo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userworklog',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='工号')),
                ('index', models.CharField(max_length=50, unique=True, verbose_name='索引')),
                ('date', models.DateField(verbose_name='日期')),
                ('needs', models.IntegerField(verbose_name='系统需求')),
                ('place', models.CharField(max_length=30, verbose_name='科室')),
                ('qsort', models.CharField(max_length=16, verbose_name='问题类型')),
                ('qdescribe', models.CharField(max_length=30, verbose_name='问题描述')),
                ('fisstatu', models.CharField(max_length=10, verbose_name='完成情况')),
                ('note', models.CharField(max_length=60, verbose_name='备注')),
            ],
            options={
                'db_table': 'Userworklog',
            },
        ),
    ]
