# Generated by Django 3.2.3 on 2021-06-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog_web', '0003_userworklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworklog',
            name='index',
            field=models.CharField(max_length=8, unique=True, verbose_name='索引'),
        ),
    ]
