# Generated by Django 3.2.3 on 2021-06-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog_web', '0004_alter_userworklog_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworklog',
            name='id',
            field=models.CharField(max_length=6, verbose_name='工号'),
        ),
        migrations.AlterField(
            model_name='userworklog',
            name='index',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='索引'),
        ),
    ]
